List

In [22]:
name=["meena","kavi","arun"]
name.append("kavya")
marks=[50,40,80]
print(name)
print(marks[2])
print(len(name))
print(len(marks))

['meena', 'kavi', 'arun', 'kavya']
80
4
3


Tuple

In [23]:
days=("Monday","Tuesday","Wednesday")
print(days[1])

Tuesday


Dictionary

In [24]:
student={
    "name":"Arun",
    "age":20
}

NumPy(Numerical Python)

In [25]:
import numpy as np
marks=np.array([80,40,30,50])
print(marks)

[80 40 30 50]


In [26]:
import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])
print(a+b)

[ 6  8 10]


In [27]:
import numpy as np
a=np.array([30,40,50])
b=np.array([16,17,20])
print(a-b)

[14 23 30]


In [28]:
import numpy as np
a=np.array([6,7,5])
b=np.array([8,9,3])
print(a*b)


[48 63 15]
