Python basic

In [36]:
name="Sakthi"
age=26
CGPA=8.5
placed=True
print("Student Name",name)
print("age",age)
print("CGPA",CGPA)
print("placed",placed)
print(type(name))
print(type(age))
print(type(CGPA))
print(type(placed))
print(len(name))



Student Name Sakthi
age 26
CGPA 8.5
placed True
<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>
6


List

In [37]:
name=["sakthi","rithi","kavi"]
name.append("mega")
marks=[50,60,90]
print(name)
print(marks[2])
print(len(name))
print(len(marks))

['sakthi', 'rithi', 'kavi', 'mega']
90
4
3


Tuple

In [38]:
days=("Mpnday","Tuesday","Wednesday")
print(days[1])

Tuesday


Dictionary

In [39]:
student={
    "name":"Arun",
    "age":20
}

NumPy(Numerical Python)

In [40]:
import numpy as np
marks=np.array([80,40,30,50])
print(marks)

[80 40 30 50]


ACTIVITY

In [41]:
import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b)
print(a**b)

[ 6  8 10]
[-4 -4 -4]
[ 5 12 21]
[0.2        0.33333333 0.42857143]
[1 2 3]
[0 0 0]
[   1   64 2187]
